version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands:
    - echo "Building version $READTHEDOCS_VERSION"
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    # Copy the prebuilt docs into the read the docs output directory 
    - cp -r docs/* $READTHEDOCS_OUTPUT/html/
